version: '3'
services:
  nginx: 
    image: rajithdocker/nginx:3.0
    container_name: prod-nginx
    restart: always
    ports:
      - 7070:7070
    depends_on:
      - easy-notes-app

  easy-notes-app:
    image: rajithdocker/easy-notes:1.0
    expose:
      - "9090"
    depends_on:
      - mysql-standalone
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-standalone:3306/${DATABASE_NAME}?useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
  
  mysql-standalone:
    image: mysql:5.6
    expose: 
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ONETIME_PASSWORD=true